import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Inter } from "next/font/google";
import { dark } from "@clerk/themes";
import "./globals.css";
import { ThemeProvider } from "./providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider appearance={{baseTheme:dark}}>
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
       attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
  <body className={inter.className}>{children}</body>
      </ThemeProvider>
    
    </html>
    </ClerkProvider>
  );
}
